/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Country
 */
export interface Country {
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    country_id?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    printable_name?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    is_visible?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    iso_3166_1_numeric?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    iso_3166_1_a3?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    iso_3166_1_a2?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    icon_url?: string;
}
