/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    currency_id?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    icon_url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Currency
     */
    is_popular?: boolean;
}
