/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
/**
 * 
 * @export
 * @interface DetailedBalanceResponse
 */
export interface DetailedBalanceResponse {
    /**
     * Number of BIND tokens posessed by current User
     * @type {number}
     * @memberof DetailedBalanceResponse
     */
    balance_in_tokens?: number;
    /**
     * Price of BIND tokens posessed by current User
     * @type {number}
     * @memberof DetailedBalanceResponse
     */
    balance_in_currency?: number;
    /**
     * 
     * @type {Currency}
     * @memberof DetailedBalanceResponse
     */
    currency?: Currency;
    /**
     * Average purchase price of BIND tokens posessed by current User
     * @type {number}
     * @memberof DetailedBalanceResponse
     */
    purchase_price?: number;
    /**
     * Current price of BIND token
     * @type {number}
     * @memberof DetailedBalanceResponse
     */
    current_price?: number;
    /**
     * Listing price of BIND token
     * @type {number}
     * @memberof DetailedBalanceResponse
     */
    listing_price?: number;
}
