/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Invitation } from './invitation';
/**
 * 
 * @export
 * @interface ListInvitations
 */
export interface ListInvitations {
    /**
     * 
     * @type {string}
     * @memberof ListInvitations
     */
    code?: string;
    /**
     * 
     * @type {Array<Invitation>}
     * @memberof ListInvitations
     */
    invites?: Array<Invitation>;
}
