/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * Contains descrtiption of an error for a User in case of user-friendly exception
     * @type {string}
     * @memberof ModelError
     */
    message: string;
    /**
     * true if a request can be repeated after getting an error
     * @type {boolean}
     * @memberof ModelError
     */
    is_retriable?: boolean;
    /**
     * Description of a non-user-friendly exception for developers
     * @type {any}
     * @memberof ModelError
     */
    data: any | null;
}
