/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
/**
 * 
 * @export
 * @interface OrderedTokensResponse
 */
export interface OrderedTokensResponse {
    /**
     * How many BIND tokens were ordered during ICO
     * @type {number}
     * @memberof OrderedTokensResponse
     */
    ordered_tokens?: number;
    /**
     * Price of all purchased BIND tokens
     * @type {number}
     * @memberof OrderedTokensResponse
     */
    ordered_tokens_price?: number;
    /**
     * 
     * @type {Currency}
     * @memberof OrderedTokensResponse
     */
    price_currency?: Currency;
    /**
     * How many BIND tokens were minted before ICO
     * @type {number}
     * @memberof OrderedTokensResponse
     */
    available_tokens?: number;
}
