/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PatchUser
 */
export interface PatchUser {
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    first_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    last_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    middle_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    birthdate?: string | null;
    /**
     * ID of a currency to set as Interface currency for User
     * @type {string}
     * @memberof PatchUser
     */
    ico_interface_currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    registration_referral_code?: string | null;
    /**
     * ID of a country
     * @type {string}
     * @memberof PatchUser
     */
    country?: string;
}
