/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaymentLinkInput
 */
export interface PaymentLinkInput {
    /**
     * ID of a currency that will be used to perform a payment
     * @type {string}
     * @memberof PaymentLinkInput
     */
    payment_currency_id?: string;
    /**
     * A fiat sum that will be spent by a User to buy BIND tokens
     * @type {number}
     * @memberof PaymentLinkInput
     */
    payment_amount?: number;
    /**
     * Amount of BIND tokens that we have promised to sell. If the purchase rate is changed during the call, method will return a human readable error
     * @type {number}
     * @memberof PaymentLinkInput
     */
    bind_amount?: number;
}
