/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RedeemStablecoinsRequest
 */
export interface RedeemStablecoinsRequest {
    /**
     * Number of redeemed tokens or stablecoins
     * @type {number}
     * @memberof RedeemStablecoinsRequest
     */
    redeem_amount: number;
    /**
     * Crypto wallet address
     * @type {string}
     * @memberof RedeemStablecoinsRequest
     */
    wallet_address: string;
}
