/* tslint:disable */
/* eslint-disable */
/**
 * BIND ICO portal API
 * Description for BIND. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bind.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StablecoinRedeemTransaction
 */
export interface StablecoinRedeemTransaction {
    /**
     * email of a user
     * @type {string}
     * @memberof StablecoinRedeemTransaction
     */
    user_email?: string;
    /**
     * BEP20 wallet of a user
     * @type {string}
     * @memberof StablecoinRedeemTransaction
     */
    wallet_address?: string;
    /**
     * amount of an operation, 100.56 means 100 dollars 56 cents
     * @type {number}
     * @memberof StablecoinRedeemTransaction
     */
    amount?: number;
}
